/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 144 --l2 146 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 157 --l2 159 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 157 --l2 161 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 158 --l2 160 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 158 --l2 162 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 159 --l2 161 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 159 --l2 163 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 160 --l2 162 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 160 --l2 164 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 161 --l2 163 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 162 --l2 164 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 162 --l2 166 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 163 --l2 167 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 164 --l2 166 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 164 --l2 168 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 166 --l2 168 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 166 --l2 170 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 167 --l2 169 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 167 --l2 171 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 168 --l2 170 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 168 --l2 172 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 169 --l2 171 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 169 --l2 173 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 170 --l2 172 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 170 --l2 174 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 171 --l2 173 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 171 --l2 175 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 172 --l2 174 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 172 --l2 176 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 173 --l2 175 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 173 --l2 177 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 174 --l2 176 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 174 --l2 178 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 175 --l2 177 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 175 --l2 179 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 176 --l2 178 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 176 --l2 180 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 177 --l2 179 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 177 --l2 181 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 178 --l2 180 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 178 --l2 182 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 179 --l2 181 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 179 --l2 183 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 180 --l2 182 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 181 --l2 183 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 181 --l2 185 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 182 --l2 186 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 183 --l2 185 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 183 --l2 187 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 185 --l2 187 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 185 --l2 189 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 186 --l2 188 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 186 --l2 190 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 187 --l2 189 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 187 --l2 191 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 188 --l2 190 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 188 --l2 192 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 189 --l2 191 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 189 --l2 193 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 190 --l2 192 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 190 --l2 194 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 191 --l2 193 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 191 --l2 195 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 192 --l2 194 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 192 --l2 196 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 193 --l2 195 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 193 --l2 197 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 194 --l2 196 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 194 --l2 198 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 195 --l2 197 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 195 --l2 199 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 196 --l2 198 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 196 --l2 200 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 197 --l2 199 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 197 --l2 201 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 198 --l2 200 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 198 --l2 202 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 199 --l2 201 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 199 --l2 203 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 200 --l2 202 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 200 --l2 204 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 201 --l2 203 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 201 --l2 205 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 202 --l2 204 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 202 --l2 206 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 203 --l2 205 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 203 --l2 207 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 204 --l2 206 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 204 --l2 208 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 205 --l2 207 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 205 --l2 209 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 206 --l2 208 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 206 --l2 210 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 207 --l2 209 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 207 --l2 211 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 208 --l2 210 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 208 --l2 212 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 209 --l2 211 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 209 --l2 213 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 210 --l2 212 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 210 --l2 214 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 211 --l2 213 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 211 --l2 215 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 212 --l2 214 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 212 --l2 216 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 213 --l2 215 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 213 --l2 217 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 214 --l2 216 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 214 --l2 218 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 215 --l2 217 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 215 --l2 219 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 216 --l2 218 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 216 --l2 220 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 217 --l2 219 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 217 --l2 221 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 218 --l2 220 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 218 --l2 222 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 219 --l2 221 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 219 --l2 223 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 220 --l2 222 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 220 --l2 224 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 221 --l2 223 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 221 --l2 225 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 222 --l2 224 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 222 --l2 226 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 223 --l2 225 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 223 --l2 227 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 224 --l2 226 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 224 --l2 228 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 225 --l2 227 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 225 --l2 229 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 226 --l2 228 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 226 --l2 230 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 227 --l2 229 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 227 --l2 231 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 228 --l2 230 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 228 --l2 232 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 229 --l2 231 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 229 --l2 233 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 230 --l2 232 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 230 --l2 234 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 231 --l2 233 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 231 --l2 235 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 232 --l2 234 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 232 --l2 236 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 233 --l2 235 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 233 --l2 237 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 234 --l2 236 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 234 --l2 238 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 235 --l2 237 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 235 --l2 239 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 236 --l2 238 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 236 --l2 240 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 237 --l2 239 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 237 --l2 241 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 238 --l2 240 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 238 --l2 242 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 239 --l2 241 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 239 --l2 243 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 240 --l2 242 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 240 --l2 244 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 241 --l2 243 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 241 --l2 245 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 242 --l2 244 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 242 --l2 246 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 243 --l2 245 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 243 --l2 247 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 244 --l2 246 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 244 --l2 248 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 245 --l2 247 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 245 --l2 249 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 246 --l2 248 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 246 --l2 250 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 247 --l2 249 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 247 --l2 251 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 248 --l2 250 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 248 --l2 252 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 249 --l2 251 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 249 --l2 253 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 250 --l2 252 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 250 --l2 254 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 251 --l2 253 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 251 --l2 255 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 252 --l2 254 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 252 --l2 256 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 253 --l2 255 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 253 --l2 257 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 254 --l2 256 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 254 --l2 258 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 255 --l2 257 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 255 --l2 259 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 256 --l2 258 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 256 --l2 260 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 257 --l2 259 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 257 --l2 261 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 258 --l2 260 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 258 --l2 262 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 259 --l2 261 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 259 --l2 263 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 260 --l2 262 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 260 --l2 264 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 261 --l2 263 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 261 --l2 265 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 262 --l2 264 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 262 --l2 266 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 263 --l2 265 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 263 --l2 267 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 264 --l2 266 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 264 --l2 268 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 265 --l2 267 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 265 --l2 269 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 266 --l2 268 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 266 --l2 270 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 267 --l2 269 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 267 --l2 271 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 268 --l2 270 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 268 --l2 272 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 269 --l2 271 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 269 --l2 273 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 270 --l2 272 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 270 --l2 274 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 271 --l2 273 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 271 --l2 275 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 272 --l2 274 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 272 --l2 276 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 273 --l2 275 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 273 --l2 277 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 274 --l2 276 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 274 --l2 278 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 275 --l2 277 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 275 --l2 279 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 276 --l2 278 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 276 --l2 280 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 277 --l2 279 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 277 --l2 281 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 278 --l2 280 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 278 --l2 282 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 279 --l2 281 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 279 --l2 283 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 280 --l2 282 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 280 --l2 284 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 281 --l2 283 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 281 --l2 285 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 282 --l2 284 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 282 --l2 286 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 283 --l2 285 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 283 --l2 287 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 284 --l2 286 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 284 --l2 288 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 285 --l2 287 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 285 --l2 289 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 286 --l2 288 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 286 --l2 290 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 287 --l2 289 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 287 --l2 291 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 288 --l2 290 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 288 --l2 292 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 289 --l2 291 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 289 --l2 293 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 290 --l2 292 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 290 --l2 294 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 291 --l2 293 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 291 --l2 295 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 292 --l2 294 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 292 --l2 296 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 293 --l2 295 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 293 --l2 297 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 294 --l2 296 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 294 --l2 298 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 295 --l2 297 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 295 --l2 299 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 296 --l2 298 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 296 --l2 300 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 297 --l2 299 --n1 0 --n2 0 --t 8
/home/g.samarth/.conda/envs/helio/bin/python /home/g.samarth/globalHelioseismology/cs_data.py --l1 298 --l2 300 --n1 0 --n2 0 --t 8
