/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 230 --lp 230 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 230 --lp 232 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 230 --lp 234 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 231 --lp 231 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 231 --lp 233 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 231 --lp 235 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 232 --lp 232 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 232 --lp 234 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 232 --lp 236 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 233 --lp 233 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 233 --lp 235 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 233 --lp 237 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 234 --lp 234 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 234 --lp 236 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 234 --lp 238 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 235 --lp 235 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 235 --lp 237 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 235 --lp 239 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 236 --lp 236 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 236 --lp 238 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 236 --lp 240 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 237 --lp 237 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 237 --lp 239 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 237 --lp 241 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 238 --lp 238 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 238 --lp 240 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 238 --lp 242 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 239 --lp 239 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 239 --lp 241 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 239 --lp 243 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 240 --lp 240 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 240 --lp 242 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 240 --lp 244 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 241 --lp 241 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 241 --lp 243 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 241 --lp 245 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 242 --lp 242 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 242 --lp 244 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 242 --lp 246 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 243 --lp 243 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 243 --lp 245 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 243 --lp 247 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 244 --lp 244 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 244 --lp 246 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 244 --lp 248 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 245 --lp 245 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 245 --lp 247 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 245 --lp 249 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 246 --lp 246 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 246 --lp 248 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 246 --lp 250 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 247 --lp 247 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 247 --lp 249 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 247 --lp 251 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 248 --lp 248 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 248 --lp 250 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 248 --lp 252 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 249 --lp 249 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 249 --lp 251 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 249 --lp 253 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 250 --lp 250 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 250 --lp 252 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 250 --lp 254 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 251 --lp 251 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 251 --lp 253 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 251 --lp 255 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 252 --lp 252 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 252 --lp 254 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 252 --lp 256 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 253 --lp 253 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 253 --lp 255 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 253 --lp 257 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 254 --lp 254 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 254 --lp 256 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 254 --lp 258 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 255 --lp 255 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 255 --lp 257 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 255 --lp 259 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 256 --lp 256 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 256 --lp 258 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 256 --lp 260 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 257 --lp 257 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 257 --lp 259 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 257 --lp 261 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 258 --lp 258 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 258 --lp 260 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 258 --lp 262 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 259 --lp 259 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 259 --lp 261 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 259 --lp 263 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 260 --lp 260 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 260 --lp 262 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 260 --lp 264 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 261 --lp 261 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 261 --lp 263 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 261 --lp 265 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 262 --lp 262 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 262 --lp 264 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 262 --lp 266 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 263 --lp 263 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 263 --lp 265 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 263 --lp 267 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 264 --lp 264 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 264 --lp 266 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 264 --lp 268 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 265 --lp 265 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 265 --lp 267 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 265 --lp 269 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 266 --lp 266 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 266 --lp 268 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 266 --lp 270 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 267 --lp 267 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 267 --lp 269 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 267 --lp 271 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 268 --lp 268 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 268 --lp 270 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 268 --lp 272 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 269 --lp 269 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 269 --lp 271 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 269 --lp 273 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 270 --lp 270 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 270 --lp 272 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 270 --lp 274 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 271 --lp 271 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 271 --lp 273 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 271 --lp 275 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 272 --lp 272 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 272 --lp 274 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 272 --lp 276 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 273 --lp 273 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 273 --lp 275 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 273 --lp 277 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 274 --lp 274 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 274 --lp 276 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 274 --lp 278 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 275 --lp 275 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 275 --lp 277 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 275 --lp 279 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 276 --lp 276 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 276 --lp 278 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 276 --lp 280 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 277 --lp 277 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 277 --lp 279 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 277 --lp 281 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 278 --lp 278 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 278 --lp 280 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 278 --lp 282 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 279 --lp 279 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 279 --lp 281 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 279 --lp 283 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 280 --lp 280 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 280 --lp 282 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 280 --lp 284 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 281 --lp 281 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 281 --lp 283 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 281 --lp 285 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 282 --lp 282 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 282 --lp 284 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 282 --lp 286 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 283 --lp 283 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 283 --lp 285 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 283 --lp 287 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 284 --lp 284 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 284 --lp 286 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 284 --lp 288 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 285 --lp 285 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 285 --lp 287 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 285 --lp 289 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 286 --lp 286 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 286 --lp 288 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 286 --lp 290 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 287 --lp 287 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 287 --lp 289 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 287 --lp 291 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 288 --lp 288 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 288 --lp 290 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 289 --lp 289 --n 0 --np 0 --find_baselines
/home/g.samarth/anaconda3/bin/python /home/g.samarth/Woodard2013/WoodardPy/cs_data.py --l 289 --lp 291 --n 0 --np 0 --find_baselines
