python /home/g.samarth/globalHelioseismology/cs_data.py --l 157 --lp 161 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 158 --lp 162 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 159 --lp 163 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 160 --lp 164 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 162 --lp 166 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 163 --lp 167 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 164 --lp 168 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 166 --lp 170 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 167 --lp 171 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 168 --lp 172 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 169 --lp 173 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 170 --lp 174 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 171 --lp 175 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 172 --lp 176 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 173 --lp 177 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 174 --lp 178 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 175 --lp 179 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 176 --lp 180 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 177 --lp 181 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 178 --lp 182 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 179 --lp 183 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 181 --lp 185 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 182 --lp 186 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 183 --lp 187 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 185 --lp 189 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 186 --lp 190 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 187 --lp 191 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 188 --lp 192 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 189 --lp 193 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 190 --lp 194 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 191 --lp 195 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 192 --lp 196 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 193 --lp 197 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 194 --lp 198 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 195 --lp 199 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 196 --lp 200 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 197 --lp 201 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 198 --lp 202 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 199 --lp 203 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 200 --lp 204 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 201 --lp 205 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 202 --lp 206 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 203 --lp 207 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 204 --lp 208 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 205 --lp 209 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 206 --lp 210 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 207 --lp 211 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 208 --lp 212 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 209 --lp 213 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 210 --lp 214 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 211 --lp 215 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 212 --lp 216 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 213 --lp 217 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 214 --lp 218 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 215 --lp 219 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 216 --lp 220 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 217 --lp 221 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 218 --lp 222 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 219 --lp 223 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 220 --lp 224 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 221 --lp 225 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 222 --lp 226 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 223 --lp 227 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 224 --lp 228 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 225 --lp 229 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 226 --lp 230 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 227 --lp 231 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 228 --lp 232 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 229 --lp 233 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 230 --lp 234 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 231 --lp 235 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 232 --lp 236 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 233 --lp 237 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 234 --lp 238 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 235 --lp 239 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 236 --lp 240 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 237 --lp 241 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 238 --lp 242 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 239 --lp 243 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 240 --lp 244 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 241 --lp 245 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 242 --lp 246 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 243 --lp 247 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 244 --lp 248 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 245 --lp 249 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 246 --lp 250 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 247 --lp 251 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 248 --lp 252 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 249 --lp 253 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 250 --lp 254 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 251 --lp 255 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 252 --lp 256 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 253 --lp 257 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 254 --lp 258 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 255 --lp 259 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 256 --lp 260 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 257 --lp 261 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 258 --lp 262 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 259 --lp 263 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 260 --lp 264 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 261 --lp 265 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 262 --lp 266 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 263 --lp 267 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 264 --lp 268 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 265 --lp 269 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 266 --lp 270 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 267 --lp 271 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 268 --lp 272 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 269 --lp 273 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 270 --lp 274 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 271 --lp 275 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 272 --lp 276 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 273 --lp 277 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 274 --lp 278 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 275 --lp 279 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 276 --lp 280 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 277 --lp 281 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 278 --lp 282 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 279 --lp 283 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 280 --lp 284 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 281 --lp 285 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 282 --lp 286 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 283 --lp 287 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 284 --lp 288 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 285 --lp 289 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 286 --lp 290 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 287 --lp 291 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 288 --lp 292 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 289 --lp 293 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 290 --lp 294 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 291 --lp 295 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 292 --lp 296 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 293 --lp 297 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 294 --lp 298 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 295 --lp 299 --n 0 --np 0 --t 0 --find_baselines
python /home/g.samarth/globalHelioseismology/cs_data.py --l 296 --lp 300 --n 0 --np 0 --t 0 --find_baselines
